// A test vector for the dashboard's owner files (owner.ts has the contract), built with node:crypto only, so the
// collector (Go) can check its encryption against the same bytes the page decrypts. Deterministic: a fixed fleet
// key and a fixed nonce (a real owner.json uses a fresh random nonce every time it is written).
//
// The plaintext rows are exactly what GET /api/limits returns on d0m1.com: each collector snapshot below goes
// through the API's own validation (api/src/lib/validate.js validateLimit), which is what the API stores and
// serves. Compare decrypted rows as JSON values, not as bytes.
//
// Usage: node pages/dashboard/testdata/owner-vector.mjs   rewrites owner-vector.json beside this file
// (owner.test.ts fails when the committed file and this generator disagree).
import { createCipheriv, createHmac } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { validateLimit } from '../../../api/src/lib/validate.js'

export const OWNER_CONTEXT = 'tokenmaxr dashboard owner v1'

/** The owner key: HMAC-SHA256 keyed with the fleet key K over the context string. */
export function deriveOwnerKey(fleetKey) {
  return createHmac('sha256', fleetKey).update(OWNER_CONTEXT, 'utf8').digest()
}

/** owner.json for one machine: AES-256-GCM, 12-byte nonce, AAD "<context>|<machine>", data = ciphertext || tag. */
export function encryptOwnerFile({ ownerKey, machine, plaintext, nonce }) {
  const cipher = createCipheriv('aes-256-gcm', ownerKey, nonce, { authTagLength: 16 })
  cipher.setAAD(Buffer.from(`${OWNER_CONTEXT}|${machine}`, 'utf8'))
  const data = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final(), cipher.getAuthTag()])
  return { schema: 1, machine, alg: 'A256GCM', nonce: nonce.toString('base64'), data: data.toString('base64') }
}

const base64url = (bytes) => Buffer.from(bytes).toString('base64url')

// What the collector holds before ghpub strips the private fields (model.LimitSnapshot), at NOW.
const NOW = new Date('2026-10-01T12:00:00Z')
const SNAPSHOTS = [
  { id: '1'.repeat(32), provider: 'anthropic', source: 'claude-code', acct: 'a_1539dc8e48fdf4d2', acctQ: 'recorded', plan: 'Max (20x)', window: 'session', label: 'owner@example.com', usedPercent: 12.5, resetsAt: '2026-10-01T15:00:00Z', observedAt: '2026-10-01T11:58:00Z', status: 'ok' },
  { id: '2'.repeat(32), provider: 'anthropic', source: 'claude-code', acct: 'a_1539dc8e48fdf4d2', acctQ: 'recorded', plan: 'Max (20x)', window: 'week', label: 'owner@example.com', usedPercent: 64, resetsAt: '2026-10-06T15:00:00Z', observedAt: '2026-10-01T11:58:00Z', status: 'ok' },
  { id: '3'.repeat(32), provider: 'anthropic', source: 'claude-code', acct: 'a_1539dc8e48fdf4d2', acctQ: 'recorded', plan: 'Max (20x)', window: 'week', scope: 'Fable', label: 'owner@example.com', usedPercent: 81, resetsAt: '2026-10-06T15:00:00Z', observedAt: '2026-10-01T11:58:00Z', status: 'ok' },
  { id: '4'.repeat(32), provider: 'anthropic', source: 'claude-code', acct: 'a_0123456789abcdef', acctQ: 'recorded', window: 'week', name: 'Example Org', label: 'work@example.org', usedPercent: 100, resetsAt: '2026-10-02T21:00:00Z', observedAt: '2026-10-01T11:40:00Z', status: 'full' },
  { id: '5'.repeat(32), provider: 'anthropic', source: 'claude-code', acct: 'a_0123456789abcdef', acctQ: 'recorded', window: 'extra', name: 'Example Org', label: 'work@example.org', detail: 'out of credits', observedAt: '2026-10-01T11:40:00Z', status: 'disabled' },
  { id: '6'.repeat(32), provider: 'openai', source: 'codex', acct: 'a_fedcba9876543210', acctQ: 'recorded', plan: 'Pro', window: 'week', label: 'owner@example.com', usedPercent: 37, resetsAt: '2026-10-05T09:30:00Z', observedAt: '2026-10-01T11:55:00Z', status: 'ok' },
  { id: '7'.repeat(32), provider: 'xai', source: 'grok-cli', acct: '', acctQ: 'unknown', plan: 'SuperGrok Heavy', window: 'plan', observedAt: '2026-10-01T11:50:00Z' },
]

export const MACHINE = 'm_0123456789ab'
export const OTHER_MACHINE = 'm_ba9876543210'
export const FLEET_KEY = Buffer.from(Array.from({ length: 32 }, (_, i) => i))
export const NONCE = Buffer.from('a0a1a2a3a4a5a6a7a8a9aaab', 'hex')

/** The rows GET /api/limits would serve for these snapshots. */
export function apiRows(snapshots = SNAPSHOTS, now = NOW) {
  return snapshots.map((snapshot) => {
    const result = validateLimit(snapshot, now)
    if (!result.ok) throw new Error(`snapshot ${snapshot.id}: ${result.error}`)
    return result.value
  })
}

export function ownerVector() {
  const ownerKey = deriveOwnerKey(FLEET_KEY)
  const items = apiRows()
  const plaintext = JSON.stringify({ v: 1, items })
  return {
    about: 'tokenmaxr dashboard owner files (pages/dashboard/owner.ts). Generated by owner-vector.mjs: do not edit.',
    fleetKey: FLEET_KEY.toString('base64'),
    context: OWNER_CONTEXT,
    ownerKey: ownerKey.toString('base64'),
    ownerKeyBase64Url: base64url(ownerKey),
    unlockFragment: `#unlock=${base64url(ownerKey)}`,
    machine: MACHINE,
    aad: `${OWNER_CONTEXT}|${MACHINE}`,
    nonce: NONCE.toString('base64'),
    plaintext,
    items,
    file: encryptOwnerFile({ ownerKey, machine: MACHINE, plaintext, nonce: NONCE }),
  }
}

export const VECTOR_PATH = fileURLToPath(new URL('./owner-vector.json', import.meta.url))

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(VECTOR_PATH, JSON.stringify(ownerVector(), null, 1) + '\n')
  console.log(`wrote ${VECTOR_PATH}`)
}
